version: "1.0"
info:
  model: int-scaffold
packages:
- name: IST_TEST_SriniProject
  gitServerName: srini_github
  gitUrl: https://github.com/chini007
  gitUsername: chini007
  gitBranch: dev
- name: Supportpkg
  gitServerName: srini_github
  gitUrl: https://github.com/chini007
  gitUsername: chini007
  gitBranch: dev
